export const bibleAbbreviations: Record<string, string[]> = {
  genesis: ['ge', 'gn'],
  exodus: ['ex', 'exod', 'exo'],
  leviticus: ['lev', 'le', 'lv'],
  numbers: ['num', 'nu', 'nm', 'nb'],
  deuteronomy: ['deut', 'de', 'dt'],
  joshua: ['josh', 'jos', 'jsh'],
  judges: ['judg', 'jdg', 'jg', 'jdgs'],
  ruth: ['ruth', 'rth', 'ru'],
  '1samuel': [
    '1 samuel',
    '1 sam',
    '1 sm',
    '1 sa',
    '1 s',
    'i sam',
    'i sa',
    '1sam',
    '1sa',
    '1s',
    '1st samuel',
    '1st sam',
    'first samuel',
    'first sam'
  ],
  '2samuel': [
    '2 samuel',
    '2 sam',
    '2 sm',
    '2 sa',
    '2 s',
    'ii sam',
    'ii sa',
    '2sam',
    '2sa',
    '2s',
    '2nd samuel',
    '2nd sam',
    'second samuel',
    'second sam'
  ],
  '1kings': [
    '1 kings',
    '1 kgs',
    '1 ki',
    '1kgs',
    '1kin',
    '1ki',
    '1k',
    'i kgs',
    'i ki',
    '1st kings',
    '1st kgs',
    'first kings',
    'first kgs'
  ],
  '2kings': [
    '2 kings',
    '2 kgs',
    '2 ki',
    '2kgs',
    '2kin',
    '2ki',
    '2k',
    'ii kgs',
    'ii ki',
    '2nd kings',
    '2nd kgs',
    'second kings',
    'second kgs'
  ],
  '1chronicles': [
    '1 chronicles',
    '1 chron',
    '1 chr',
    '1 ch',
    '1chron',
    '1chr',
    '1ch',
    'i chron',
    'i chr',
    'i ch',
    '1st chronicles',
    '1st chron',
    'first chronicles',
    'first chron'
  ],
  '2chronicles': [
    '2 chronicles',
    '2 chron',
    '2 chr',
    '2 ch',
    '2chron',
    '2chr',
    '2ch',
    'ii chron',
    'ii chr',
    'ii ch',
    '2nd chronicles',
    '2nd chron',
    'second chronicles',
    'second chron'
  ],
  ezra: ['ezra', 'ezr', 'ez'],
  nehemiah: ['neh', 'ne'],
  tobit: ['tob', 'tb'],
  judith: ['jth', 'jdth', 'jdt'],
  esther: ['est', 'esth', 'es'],
  '1maccabees': [
    '1 maccabees',
    '1 macc',
    '1 mac',
    '1maccabees',
    '1macc',
    '1mac',
    '1ma',
    '1m',
    'i maccabees',
    'i macc',
    'i mac',
    'i ma',
    '1st maccabees',
    'first maccabees'
  ],
  '2maccabees': [
    '2 maccabees',
    '2 macc',
    '2 mac',
    '2maccabees',
    '2macc',
    '2mac',
    '2ma',
    '2m',
    'ii maccabees',
    'ii macc',
    'ii mac',
    'ii ma',
    '2nd maccabees',
    'second maccabees'
  ],
  job: ['job', 'jb'],
  psalms: ['ps', 'psalm', 'pslm', 'psa', 'psm', 'pss'],
  proverbs: ['prov', 'pro', 'prv', 'pr'],
  ecclesiastes: ['eccles', 'eccle', 'ecc', 'ec', 'qoh'],
  songofsongs: ['song of solomon', 'song', 'song of songs', 'sos', 'so', 'canticle of canticles', 'canticles', 'cant'],
  wisdom: ['wisdom of solomon', 'wisd of sol', 'wisdom', 'wis', 'ws'],
  sirach: ['sir'],
  isaiah: ['isa', 'is'],
  jeremiah: ['jer', 'je', 'jr'],
  lamentations: ['lam', 'la'],
  baruch: ['bar'],
  ezekiel: ['ezek', 'eze', 'ezk'],
  daniel: ['dan', 'da', 'dn'],
  hosea: ['hos', 'ho'],
  joel: ['joel', 'jl'],
  amos: ['amos', 'am'],
  obadiah: ['obad', 'ob'],
  jonah: ['jonah', 'jnh', 'jon'],
  micah: ['mic', 'mc'],
  nahum: ['nah', 'na'],
  habakkuk: ['hab', 'hb'],
  zephaniah: ['zeph', 'zep', 'zp'],
  haggai: ['hag', 'hg'],
  zechariah: ['zech', 'zec', 'zc'],
  malachi: ['mal', 'ml'],
  matthew: ['matt', 'mt'],
  mark: ['mark', 'mrk', 'mar', 'mk', 'mr'],
  luke: ['luke', 'luk', 'lk'],
  john: ['john', 'joh', 'jhn', 'jn'],
  acts: ['acts of the apostles', 'acts', 'act', 'ac'],
  romans: ['rom', 'ro', 'rm'],
  '1corinthians': [
    '1 corinthians',
    '1 cor',
    '1 co',
    'i cor',
    'i co',
    '1cor',
    '1co',
    'i corinthians',
    '1corinthians',
    '1st corinthians',
    'first corinthians'
  ],
  '2corinthians': [
    '2 corinthians',
    '2 cor',
    '2 co',
    'ii cor',
    'ii co',
    '2cor',
    '2co',
    'ii corinthians',
    '2corinthians',
    '2nd corinthians',
    'second corinthians'
  ],
  galatians: ['gal', 'ga'],
  ephesians: ['eph', 'ephes'],
  philippians: ['phil', 'php', 'pp'],
  colossians: ['col', 'co'],
  '1thessalonians': [
    '1 thessalonians',
    '1 thess',
    '1 thes',
    '1 th',
    'i thessalonians',
    'i thess',
    'i thes',
    'i th',
    '1thessalonians',
    '1thess',
    '1thes',
    '1th',
    '1st thessalonians',
    '1st thess',
    'first thessalonians',
    'first thess'
  ],
  '2thessalonians': [
    '2 thessalonians',
    '2 thess',
    '2 thes',
    '2 th',
    'ii thessalonians',
    'ii thess',
    'ii thes',
    'ii th',
    '2thessalonians',
    '2thess',
    '2thes',
    '2th',
    '2nd thessalonians',
    '2nd thess',
    'second thessalonians',
    'second thess'
  ],
  '1timothy': [
    '1 timothy',
    '1 tim',
    '1 ti',
    'i timothy',
    'i tim',
    'i ti',
    '1timothy',
    '1tim',
    '1ti',
    '1st timothy',
    '1st tim',
    'first timothy',
    'first tim'
  ],
  '2timothy': [
    '2 timothy',
    '2 tim',
    '2 ti',
    'ii timothy',
    'ii tim',
    'ii ti',
    '2timothy',
    '2tim',
    '2ti',
    '2nd timothy',
    '2nd tim',
    'second timothy',
    'second tim'
  ],
  titus: ['titus', 'tit', 'ti'],
  philemon: ['philem', 'phm', 'pm'],
  hebrews: ['heb'],
  james: ['james', 'jas', 'jm'],
  '1peter': [
    '1 peter',
    '1 pet',
    '1 pe',
    '1 pt',
    '1 p',
    'i pet',
    'i pt',
    'i pe',
    '1peter',
    '1pet',
    '1pe',
    '1pt',
    '1p',
    'i peter',
    '1st peter',
    'first peter'
  ],
  '2peter': [
    '2 peter',
    '2 pet',
    '2 pe',
    '2 pt',
    '2 p',
    'ii peter',
    'ii pet',
    'ii pt',
    'ii pe',
    '2peter',
    '2pet',
    '2pe',
    '2pt',
    '2p',
    '2nd peter',
    'second peter'
  ],
  '1john': [
    '1 john',
    '1 jhn',
    '1 jn',
    '1 j',
    '1john',
    '1jhn',
    '1joh',
    '1jn',
    '1jo',
    '1j',
    'i john',
    'i jhn',
    'i joh',
    'i jn',
    'i jo',
    '1st john',
    'first john'
  ],
  '2john': [
    '2 john',
    '2 jhn',
    '2 jn',
    '2 j',
    '2john',
    '2jhn',
    '2joh',
    '2jn',
    '2jo',
    '2j',
    'ii john',
    'ii jhn',
    'ii joh',
    'ii jn',
    'ii jo',
    '2nd john',
    'second john'
  ],
  '3john': [
    '3 john',
    '3 jhn',
    '3 jn',
    '3 j',
    '3john',
    '3jhn',
    '3joh',
    '3jn',
    '3jo',
    '3j',
    'iii john',
    'iii jhn',
    'iii joh',
    'iii jn',
    'iii jo',
    '3rd john',
    'third john'
  ],
  jude: ['jude', 'jud', 'jd'],
  revelation: ['rev', 're', 'the revelation']
};

export const abbreviationsToUJSCCBBook = Object.keys(bibleAbbreviations).reduce((result, book) => {
  const abbreviations = bibleAbbreviations[book];
  for (const abbreviation of abbreviations) {
    result[abbreviation] = book;
  }
  return result;
}, {} as Record<string, string>);

const bibleBooksAbbreviationRegexString = `(${Object.keys(abbreviationsToUJSCCBBook).join('|')})`;

const bibleAbbreviationRegexString = `${bibleBooksAbbreviationRegexString}[ ]*([0-9]+)[ ]*[:]{0,1}[ ]*([0-9]+)?(?:[ ]*[-]{1}[ ]*[0-9]+)?`;

export const bibleAbbreviationRegex = new RegExp(
  bibleAbbreviationRegexString,
  'i'
);

export const bibleAbbreviationStrictRegex = new RegExp(
  `^${bibleAbbreviationRegexString}$`,
  'i'
);

console.log('bibleBooksAbbreviationRegexString', `"${bibleBooksAbbreviationRegexString}"`, bibleAbbreviationRegex);
